services:
  database:
    image: 'postgres:latest'
    container_name: ecommerce-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: eComDB
      POSTGRES_PASSWORD: 092000The
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge
